### ISSUE TITLE
Unclear if anything was uploaded/reported successfully to mergify

### ISSUE THREAD

**Issue by yarikoptic** [Mergifyio/pytest-mergify#118]
Reincarnating #113 (do not have permissions to reopen).  The issue remains that it is unclear if anything was uploaded or failed to upload.

E.g. now account is active but nothing appears on dashboard

![Image](https://github.com/user-attachments/assets/dbf4130e-fe45-4e33-80c6-9153b5276b4a)

and nothing in a sample CI run log, e.g. https://github.com/con/duct/actions/runs/14972857670/job/42057681821?pr=271 suggests that the present mergify plugin

```
plugins: cov-6.1.1, mergify-2025.4.10.1
```

did try to upload anything or not, and if tried but failed -- why failed.  Could there be log messages from mergify plugin to inform user

- whether mergify plugin is "active"  or not (if there is difference from it being merely present/installed) . E.g. if no token is present in env - "not active due to missing MERGIFY_TOKEN env var"
- whether any information would be uploaded or not
- whether upload has successes or not (e.g. "authentication failed, please verify the token {token[:10]}...")

that should simplify user's troubleshooting of interactions with mergify

**Comment by jd** [comment]
Hi @yarikoptic !
The fact that you do not have any job execution there means the integration with GitHub Actions is not enabled.
You need to enable it here for your repository:

![Image](https://github.com/user-attachments/assets/423e6c3a-55ab-4081-99f2-fc71ada89826)

**Comment by jd** [comment]
As for `pytest-mergify`, when installed and configured, it does print information. I think the problem is `tox` is removing the environment variable such as `CI=true`. You need to make sure `CI` and `MERGIFY_TOKEN` are passed down to `pytest`.

**Comment by yarikoptic** [comment]
Great, thanks @jd !   I did enable 

![Image](https://github.com/user-attachments/assets/0f0b98e6-4e1a-46fc-b6bc-d1756d31f1f9)

might be desired to be not needed -- if information is communicated, should ideally be autoenabled; also mentioned in docs on https://docs.mergify.com/ci-insights/ ; also the fact that relies on CI env var;

I have pushed configuration change for `tox` to pass `CI` variable in addition to already passed `MERGIFY_TOKEN` in https://github.com/con/duct/pull/271/commits/12755303c028a5083962cce40300afa03a6b190c#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R16 ; but not sure if there is `CI` variable defined by github actions since I see in https://github.com/con/duct/actions/runs/15004183171/job/42158494571?pr=271 only

```
Run tox -e pyci -- -vv --cov-report=xml
  tox -e pyci -- -vv --cov-report=xml
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.13.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.13.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.3/x64
    Python[2](https://github.com/con/duct/actions/runs/15004183171/job/42158494571?pr=271#step:5:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/con/duct/actions/runs/15004183171/job/42158494571?pr=271#step:5:3).13.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.3/x6[4](https://github.com/con/duct/actions/runs/15004183171/job/42158494571?pr=271#step:5:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.3/x64/lib
    MERGIFY_TOKEN: ***
```

which is odd [since I tested in the next commit](https://github.com/con/duct/actions/runs/15004330197/job/42158993052) and there is CI variable as there should be, so not sure why not passed or not printed here... verified that it is there, and got finally to see the "Unable to determine repository name; test results will not be uploaded" from the mergify.

FWIW

- IMHO would still be useful if mergify reported "mergify is not activated since neither CI env var is set, nor ..."

As for the repository not found, I realized it would also need to pass the GITHUB_ env vars, added those, so now it runs and we get 

```
================================== Mergify CI ==================================
MERGIFY_TEST_RUN_ID=356e07bd2d4d2681
```

reported!  But dashboard remained blank!

![Image](https://github.com/user-attachments/assets/45cf8003-5cff-44eb-81a4-4c0963febb3c)

and then I saw that it has default filter - to apply only to branch `main`!  removing filter showed runs etc!!  IMHO

- by default no filter should be provided, or it should be smart to not filter until there is something in main branch?


Now the question is on what "insights" I should see (since nothing is reported back to PR apparently :-( ) but that would be a separate issue
